### ISSUE TITLE
What should we call the files for 2D Lab and 1D Lab

### ISSUE THREAD

**Issue by brandonLi8** [phetsims/collision-lab#14]
In #13, I am adding a "2D Lab" screen that is in the mockups. Naming the folder was easy: `2DLab`.

But when it came to creating the `2DLabScreen.js`, I was not able to create the module since I cannot declare a variable/class name with a number as the first character.

What is the PhET convention to dealing with these scenarios?

**Comment by brandonLi8** [comment]
<details> <summary>Slack discussion:</summary>

```
Brandon Li 12:14 PM
I’m working on Collision Lab and there is a screen in the mockups called “1D Lab”. However, I am not able to make the subsequent files (like 1DLabScreen.js) since I cannot declare a variable/class name with the first character as a number.
What is the PhET convention to dealing with these cases?

Ariel Paul 12:15 PM
@Brandon Li my naive thought would be OneD

Chris Malley 12:15 PM
I’d ask the design team if it’s OK to rename the screen to “Lab 1D”.

Martin Veillette:house_with_garden: 12:15 PM
in vector addition, we have Explore1D

Chris Malley 12:16 PM
Right, not “1D Explore” and “2D Explore”
Is there by any chance a “2D Lab” screen?

Brandon Li 12:16 PM
yes

Chris Malley 12:18 PM
My recommendation would be to rename the screens “Lab 1D” and “Lab 2D”, in which case the filename problem goes away.  If that doesn’t fly, then OneDLab.js and TwoDLab.js is only mildly offensive.

Amy Rouinfar 12:21 PM
I’d veto “OneD” if that string would ever be visible to users. There’s some nuance to the string ordering. Generally, we talk about 1D collisions and 2D collisions, so “1D Lab” is a bit more natural sounding in this context. (As opposed to “Explore 1D” where you’re exploring vectors in 1D.) I could live with “Lab 1D” if @ariel is also ok with it.

Ariel Paul 12:22 PM
Lab 1D is not so good
1D Lab is definitely more natural sounding

Martin Veillette:house_with_garden: 12:23 PM
The OneDLab would not be public facing, it will be the name of a directory

Chris Malley 12:23 PM
Some variation of OneD and TwoD would appear in the PhET-iO data stream, if we followed naming conventions.  But otherwise not visible in the UI.

So yes, it is public facing.

Brandon Li 12:23 PM
Could we do “Explore 1D” like VA?

Amy Rouinfar 12:24 PM
I just don’t want to call the screen “OneD” but I’m ok with it in the data stream. That’s not really student-facing.

Chris Malley 12:24 PM
Tandem names will be prefixed with collision-lab.oneDScreen and  collision-lab.twoDScreen.
… unless we make an exception there as well and use collision-lab.1DScreen and  collision-lab.2DScreen. I don’t know if that’s legal or not in PhET-iO-land. (edited) 

```
</details>

**Comment by brandonLi8** [comment]
<details> <summary>Another Slack discussion:</summary>

```

Chris Malley Today at 12:24 PM
Tandem names will be prefixed with collision-lab.oneDScreen and  collision-lab.twoDScreen.

Michael Kauzmann  18 minutes ago
collisionLab.oneDScreen but yes you are correct they will be public to PhET-iO.

Chris Malley  17 minutes ago
Would collisionLab.1DScreen be a valid tandem name?

Michael Kauzmann  16 minutes ago
Yes, we don't accept hyphens as far as I know. All screens and sim names are converted to camel case.

Chris Malley  15 minutes ago
So it’s OK for a token in a tandem name to start with a number?

Chris Malley  15 minutes ago
“1Dscreen” is not converting OneDScreen to camel case.

Michael Kauzmann  14 minutes ago
Oh sorry, I was focused on the sim section. I don't think we limit the starts of tandem names to chars

Chris Malley  14 minutes ago
It’s a possible exception that we discussed in the dev-public channel.

Michael Kauzmann  14 minutes ago
I see no problem with it, and it will likely work on master, so I guess go for it!

Michael Kauzmann  14 minutes ago
checking

Michael Kauzmann  13 minutes ago
currently must be a string, and pass this regex:  /^[a-zA-Z0-9~]+$/

Michael Kauzmann  13 minutes ago
So yeah seems fine to me.

Chris Malley  12 minutes ago
The entire tandem, or each token?

Michael Kauzmann  12 minutes ago
each token

Michael Kauzmann  12 minutes ago
Feel free to make an issue if it seems problematic to you, otherwise I think we are fine leaving it alone.

Chris Malley  11 minutes ago
Given the convention of camelcasing variable and class names, that seems like the wrong regex.

Michael Kauzmann  9 minutes ago
Tagging @Brandon Li @samreid @chrisklus for comment.
```

**Comment by arouinfar** [comment]
Discussed with @brandonLi8 and @ariel-phet over Slack (conversation below). For a variety of reasons, it is undesirable to start a screen name with a number, such as "1D Lab".  Alternatives include:
* Explore 1D/2D
* Lab 1D/2D
* Investigate 1D/2D
* Analyze 1D/2D
* Experiment 1D/2D

<details><summary>Slack Discussion</summary>

Ariel Paul 3:14 PM
For me, I think my thinking has probably changed since the last time we discussed
We definitely went a certain way in Vector Addition to keep things consistent
Consistency with the iO ID's seems for me to outweigh the name, I am not super tied to "1D Lab"
I think we could go with something like "Explore 1D" and "Explore 2D" - although we usually have "Explore" screens when we also have a lab

Brandon Li  3:18 PM
Would it be out of the picture to only have a “Lab” screen that has a 1D and a 2D scene (similar to polar vs rectangular in Vector addition)?

Ariel Paul 3:19 PM
@brandonLi8 I think so...breaking it up into screens the way we have is better for teachers
This way they can tell students to only go to the 1D screen or launch the sim with only the 1D screen
So it is a more powerful and seamless scaffolding of the ideas
I am going to look at some synonyms, but Explore 1D and Explore 2d would work just fine for me. "Lab in 1D" "Lab in 2D" might also be an alternative

Brandon Li  3:21 PM
Ok. +1 for “Explore 1D” and “Explore 2D”

Ariel Paul 3:22 PM
I am sure @arouinfar will have some further thoughts

Amy Rouinfar  3:22 PM
Sorry, in an interview, can’t really follow the discussion, but I’ll reply as soon as I can.

Amy Rouinfar 4:00 PM
We usually reserve “Explore” for more introductory screens. This sim already has an “Intro” screen, so the flow of Intro, Explore 1D, Explore 2D sounds a bit strange to me.
I’d prefer “Lab 1D” to “Lab in 1D”. I think it’s a little weird to include a preposition in a screen name.
“Lab 1D” doesn’t have the same flow as “Explore 1D”, and I think part of it is that “Explore” is a verb.
Maybe “Experiment 1D”? Though you could interpret “experiment” as a noun or verb here.
How blocking is this @brandonLi8? I was planning to request design meeting time this week, and this might be a good conversation to have with Kathy.

Brandon Li 4:08 PM
That’s fine. I have a lot of work in the common directory so it should be a while before I need to create the Lab screens.

Ariel Paul 4:12 PM
Investigate 1D is what I really want if I could think of a shorter word for Investigate
Perhaps Analyze 1D

Amy Rouinfar  4:19 PM
I’ll add all of the suggestions to the issue and tag it for design meeting.

</details>

**Comment by brandonLi8** [comment]
For now, I'm going with Explore 1D/ 2D to start integrating 1D into the model. I, of course, can change this if we decide on some other name.

**Comment by brandonLi8** [comment]
From design meeting 6/25/20, we decided to stick with Explore 1D/2D. Closing.
