### ISSUE TITLE
Investigate use/need for TwoVector

### ISSUE THREAD

**Issue by brandonLi8** [phetsims/collision-lab#15]
In the flash sim, there is a utility class called `TwoVector` which contains data of a previous vector.

@veillette went ahead and added it to the repo.

Right now, I don't see the use of this class and I don't like the name of `TwoVector` (seems to vague to me)

This issue is meant to track our discussions of the use/need of this class.

**Comment by veillette** [comment]
In Flash, the main purpose of TwoVector class is that you can recall the previous value of a vector.

The methods related to Xlast, YLast  were called twice in the model. All of them have to do with determine the exact time of the collision.  The idea is that the collision may occur between two time frames, and lead to errors.
 
At this point, I think it may not be needed, or at least it can be replaced by a model Ball that keep track of its position and its previous position.

I personally prefer to deal directly with Vector2 since it has a lot of convenient methods (that probably didn't exist in flash) so I would be in favor of removing TwoVector.

**Comment by brandonLi8** [comment]
In the commit above, I added the following properties:
```
      // @public (read-only) massProperty - Property of the mass of the ball (kg)
      this.massProperty = new NumberProperty( mass );

      // @public (read-only) positionPropety - Property of the center of the ball's position.
      this.positionPropety = new Vector2Property( position );

      // @public (read-only) velocityProperty - Property of the velocity of the center of mass of the ball.
      this.velocityProperty = new Vector2Property( velocity );
```
This should replace the need for `TwoVector` as the properties should be updated at each step call  and properties have built in integration of previous values.

**Comment by veillette** [comment]
Although properties would solve the problems of getting the old values of a vector, it may be a performance bottleneck.

**Comment by veillette** [comment]
The TwoVector class was removed. Closing
