### ISSUE TITLE
User reported issue: collide ball outside of reflecting border

### ISSUE THREAD

**Issue by oliver-phet** [phetsims/collision-lab#150]
Reported via phethelp, reproduced using various conditions:
<img width="1680" alt="image" src="https://user-images.githubusercontent.com/5090275/90813602-0f483500-e2e5-11ea-947f-88535b432eb6.png">

1. Explore 1D
2. Max/min balls
3. Position A -.5, velocity .5m/s
4. Position B 0, velocity .5m/s
5.  Elasticity to 90% (various issues occur at any value <100%)

I'm noticing a lot of weird issues that may be unrelated to reflecting border and seem to show up when Mass B >= 2.8kg

Name: ‪Collision Lab‬
URL: https://phet.colorado.edu/sims/html/collision-lab/latest/collision-lab_en.html
Version: 1.0.1 2020-08-14 18:19:15 UTC
Features missing: touch
Flags: pixelRatioScaling
User Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_6) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/13.1.2 Safari/605.1.15
Language: en
Window: 1680x987
Pixel Ratio: 2/1
WebGL: WebGL 1.0
GLSL: WebGL GLSL ES 1.0 (1.20)
Vendor: WebKit (WebKit WebGL)
Vertex: attribs: 16 varying: 15 uniform: 1024
Texture: size: 16384 imageUnits: 16 (vertex: 16, combined: 16)
Max viewport: 8192x8192
OES_texture_float: true
Dependencies JSON: {}

**Comment by brandonLi8** [comment]
I'll investigate.

**Comment by brandonLi8** [comment]
Tested the exact same setup on master. No issues found.

<details><summary>sample (master)</summary>

![*](https://user-images.githubusercontent.com/42391580/90815690-5257d780-e2e8-11ea-9d91-b275304009de.gif)

</details>

Then tested the setup on https://phet.colorado.edu/sims/html/collision-lab/latest/collision-lab_en.html and the problem is there. 


<details><summary>sample (deployed prototype)</summary>


![*](https://user-images.githubusercontent.com/42391580/90816105-f9d50a00-e2e8-11ea-946b-fa344f95e179.gif)

</details>


A lot of things changed since the prototype was deployed in #126. Looks like this fixed itself!

**Comment by brandonLi8** [comment]
@oliver-phet, @arouinfar what should we do from here. I confirmed that this is no longer a bug. Do we let the user know? Re-deploy another prototype? Or close and move forwards for the first "production" (non-prototype) version?

**Comment by oliver-phet** [comment]
I'll email the user either way.

**Comment by arouinfar** [comment]
@brandonLi8 if master is in a good state, I think we should redeploy the prototype.

**Comment by arouinfar** [comment]
@brandonLi8 actually, we can wait to redeploy until testing in https://github.com/phetsims/QA/issues/537 wraps up.

**Comment by KatieWoe** [comment]
Using described set up, did not see this in 1.1.0 dev.13. Will reopen if something else seems to happen that is similar.
