### ISSUE TITLE
performance sign-off

### ISSUE THREAD

**Issue by brandonLi8** [phetsims/collision-lab#157]
This is listed as a "standard GitHub issue" in the code-review checklist. The lead designer must sign off on performance.

**Comment by arouinfar** [comment]
There are not any performance issues on my older MacBook Pro, but I don't have access to our usual test devices. I believe @ariel-phet has done some testing on lower performing devices, so I'll defer to him for the sign-off.

**Comment by ariel-phet** [comment]
@jonathanolson let me know when you a version to test with performance enhancements.

**Comment by jonathanolson** [comment]
Can you try out https://phet-dev.colorado.edu/html/collision-lab/1.1.0-dev.7/phet/collision-lab_en_phet.html to see how the performance is? Also there may be some room for optimization on the "paths" view, since it's creating a large number of data points that are ALL being drawn EVERY frame. It would require a lot more complexity to optimize, so I wouldn't want to do that prematurely.

**Comment by ariel-phet** [comment]
@jonathanolson looking on iPad Air 2 iOS 14.0.1 things are looking solid (with 4 balls going, paths on, momenta diagram, and "more data" frame rate around 40 fps and looks acceptable. My home desktop stays solidly at 60 fps with these same options all active. I think we can go ahead with performance sign off here.
