### ISSUE TITLE
Kinetic Energy reads at 0 even with movement

### ISSUE THREAD

**Issue by KatieWoe** [phetsims/collision-lab#162]
For https://github.com/phetsims/QA/issues/537
I noticed that if the masses are small enough/slow enough, the energy will read as 0.00. This is clearly due to rounding, but could lead to incorrect ideas. I think a better solution in this case would be <0.01. It should still read 0.00 in cases where this is true though.
![Screenshot 2020-08-25 at 4 46 49 PM](https://user-images.githubusercontent.com/41024075/91235981-0778fe00-e6f4-11ea-87d3-5fca89205afb.png)

**Comment by arouinfar** [comment]
Thanks for the suggestion @KatieWoe. 

Rounding issues of this sort appear in lots of sims. Our general thought has been that these situations can lead to productive discussions about precision, so we don't tend to do anything about it. One exception to this has been the ammeter readout in CCK, where we decided to add an extra decimal place when the value dipped below `0.00`, see https://github.com/phetsims/circuit-construction-kit-common/issues/290. There, it was possible for a very incongruent visual (lit light bulb) and value (current reading of 0.00 A). Adding an extra decimal place does not actually remove this issue, but it makes it much less likely for a student to encounter.

This case is somewhat analogous in that we see moving objects with an apparent KE of 0.00 J. We could follow the CCK model and add an extra decimal place, but I don't think it would make much of a difference because it's easy to have a KE < 0.001 J with visibly moving balls. The suggestion to change the display to something like `KE < 0.01 J` would be nice conceptually, but we might encounter floating point issues when switching it back to `KE = 0.00 J` when the balls are at rest.

The velocity values are provided in the sim, making the KE calculation really straightforward. For this sim, I think I'd leave things the way they are, but I'll make a note about precision in the Teacher Tips.
