### ISSUE TITLE
State oddly saved if ball bumped off screen

### ISSUE THREAD

**Issue by arouinfar** [phetsims/collision-lab#163]
For https://github.com/phetsims/QA/issues/537 and related to #100.

It's generally rare to completely lose a ball when it is bumped away from its neighbors. However, after an inelastic collision, balls are grouped by a wall. Clicking on a middle ball can cause it to be bumped out of bounds. When trying to recover it with the restart button, the lost ball will return to its previously saved state, but the other balls will remain where they were with the lost ball was clicked.

@brandonLi8 this behavior seems odd to me. Can all balls return to their previously saved states? If not, I'm ok with the partially saved state since it allows the user to easily retrieve the lost ball.

Steps to reproduce: 
1. Explore 1D
2. 3 Balls, Elasticity 0%
3. Play
4. Balls will end up grouped at the left wall
![image](https://user-images.githubusercontent.com/8419308/91236964-97b84280-e6f6-11ea-94d5-681b03bbc8c2.png)
5. Click (and hold) Ball 2, and it will snap a bit to the left (closest tick mark)
<img width="810" alt="Screen Shot 2020-08-25 at 5 15 54 PM" src="https://user-images.githubusercontent.com/8419308/91237030-c0d8d300-e6f6-11ea-9493-622df65f3b83.png">
6. Release Ball 2, and it will disappear. (Likely bumped to the left of Ball 1.)

![image](https://user-images.githubusercontent.com/8419308/91237084-e82fa000-e6f6-11ea-9b1a-0eace799b505.png)

7. Press restart button, and the state is oddly restored

![image](https://user-images.githubusercontent.com/8419308/91237125-09908c00-e6f7-11ea-99e1-81e3fd1ea9ed.png)

**Comment by brandonLi8** [comment]
@arouinfar I confirmed that the ball is being "bumped" to the left of ball1.

But I don't believe that this is actually a bug.

Restart/states work because at the END of when any ball is manipulated, every balls state is saved,  **if and only if** it is in-bounds. This decision was described in https://github.com/phetsims/collision-lab/issues/90#issuecomment-642326077, where @arouinfar  said:
>  but only saving the state if the balls are in bounds sounds reasonable to me.

So essentially what is happening in this scenario is:
1. Ball2 is snapped out of bounds.
2. Since the user just finished manipulating the system, every ball that is in bounds is saved, which is ball 1 and 3. Notice that ball2's state is not saved to the out-of-bounds position, and its most recent save is the starting state.
3. Restart then sets the properties of the balls to the most recent state. For balls 1 and 3, it is already in the most recent state. For ball2, its most recently saved state is the starting state (when the sim was loaded).

**Comment by arouinfar** [comment]
> we could slightly alter this behavior; the states are always grouped as one, so when the user is finished manipulating AND none of the balls are out-of-bounds, ALL of the states of every ball is saved. If any of the balls are out-of-bounds, NONE of the states are saved. If that makes sense.

I would prefer this all-or-nothing approach to saving the state @brandonLi8.

**Comment by brandonLi8** [comment]
OK. Done in the commit above. Back to @arouinfar.

**Comment by arouinfar** [comment]
Looks good in master @brandonLi8.
