### ISSUE TITLE
We need a grid for collisionlab

### ISSUE THREAD

**Issue by alex-schor** [phetsims/collision-lab#22]
![image](https://user-images.githubusercontent.com/55298218/65728548-872bc200-e078-11e9-9f11-512eeac69f38.png)

**Comment by brandonLi8** [comment]
What should we call this view?
Typically the view and the model match names and I have created a `PlayArea.js` model.

Should I rename this model to `Grid.js` to match the view?
Or should we rename the view to `PlayAreaNode.js`?
Or perhaps rename both of them to `Graph.js` and `GraphNode.js`?

**Comment by brandonLi8** [comment]
On second thought, maybe we don't need a corresponding model. This sim doesn't have multiple scenes so all the properties of the play area can be in the common model.

**Comment by veillette** [comment]
There are many ways we can go about it.

I also like to have a symmetry between model and view component. I think we should still have a playAreaNode to match PlayArea Model. Perhaps GridNode can be a child of PlayAreaNode. As far as having a grid.js, I'm not sure it is necessary but we can. 

I'm also open to idea to rename GridNode.js. I don't think GraphNode is appropriate since it is not a graph (unllike in vector-addition). 

Collision-lab is about a billiard game, so we may try to think along these lines. The flash implementation had Table.as to indicate it was a pool table.
Of course a pool table doesn't have a grid.
If you can think of a better name, let me know.

**Comment by brandonLi8** [comment]
@veillette I like `PlayArea.js` and `PlayAreaNode.js`.

**Comment by brandonLi8** [comment]
In the commit above, I created a skeleton for the `PlayAreaNode.js`. 

The docstring looks like:
```
/**
 * View for the PlayArea, which includes:
 *  - The borders of the PlayArea as well as the grid lines
 *  - The dashed lines that indicate the origin // TODO is this what the dashed lines in the mock up indicate?
 *  - The label of the total kinetic energy in the PlayArea
 *  - The CenterOfMass node
 */
```

and has this api:
```
    /**
     * @param {PlayArea} playArea
     * @param {BooleanProperty} gridVisiblityProperty
     * @param {BooleanProperty} kineticEnergyVisiblityProperty
     * @param {BooleanProperty} centerOfMassVisiblityProperty
     */
    constructor( playArea, gridVisiblityProperty, kineticEnergyVisiblityProperty, centerOfMassVisiblityProperty ) {
```
In my opinion, we should approach this like `Vector Addition` and migrate the views associated into this file (including `GridNode`). Thoughts?

**Comment by veillette** [comment]
I agree with @brandonLi8 that GridNode should live within PlayAreaNode.

**Comment by veillette** [comment]
Work done here. Closing
