### ISSUE TITLE
Implementation of Ball Values Panel

### ISSUE THREAD

**Issue by brandonLi8** [phetsims/collision-lab#27]
This issue is to track the implementation of `BallValuesPanel` which looks like: 
![image](https://user-images.githubusercontent.com/42391580/66075939-e034a380-e519-11e9-8578-abba1f7c5a39.png)

## API
I have already created a skeleton of the panel. This is the current api:
```
    /**
     * @param {ObservableArray.<Ball>} balls - collections of particles inside the container
     * @param {BooleanProperty} modeDataProperty - Property that indicates if the "More Data" checkbox is checked.
     */
    constructor( balls, moreDataProperty ) {
```
Maybe it should take in `PlayArea` instead of just the balls?

## Display
It looks like when "more data" is unchecked, it only displays a slider to adjust the masses and when it is checked, it displays number displays of the mass, v, position, and p. Not sure if this is the case for **all** screens.

I think we should approach this like the `InspectVectorPanel` of Vector addition, where we create both "displays" and simply toggle the visibility based on `modeDataVisibilityProperty`. Thoughts?

**Comment by arouinfar** [comment]
> It looks like when "more data" is unchecked, it only displays a slider to adjust the masses and when it is checked, it displays number displays of the mass, v, position, and p. Not sure if this is the case for all screens.

Yes, that's correct. This behavior will appear on all screens. Additionally, when More Data is checked, clicking on one of the fields will summon a keypad so the user can directly enter the value.

[Projectile Motion](https://phet.colorado.edu/sims/html/projectile-motion/latest/projectile-motion_en.html?screens=4) has an example of this, when the Custom projectile is selected.
![image](https://user-images.githubusercontent.com/8419308/66089632-61516200-e53d-11e9-88d0-00525d8f3eae.png)

However, due to space constraints, we will not be including the yellow edit buttons in the Collision Lab design.

**Comment by arouinfar** [comment]
As a side note, the screenshot at the top of https://github.com/phetsims/collision-lab/issues/27#issue-501687285 shows the x & y coordinates of the 2nd ball highlighted in yellow. That is because it comes from a mockup where ball 2 was being dragged around. If instead the velocity vector was being dragged, the corresponding v_x and v_y fields would be yellow instead.

**Comment by veillette** [comment]
The keypad will need to support negative signs, since both position and velocity can be negative.

**Comment by veillette** [comment]
@brandonLi8 , I think the API with Balls should be sufficient. In addition though, it should include the model.playProperty, so that we can suspend/restart the animation while the data is entered/validated.

**Comment by arouinfar** [comment]
@veillette @brandonLi8 `area-model-algebra` and `area-model-multiplication` have a keypad which supports a negative sign. I think we can use the same layout here.

![image](https://user-images.githubusercontent.com/8419308/66225685-3a5a7380-e696-11e9-8bac-cfb96c78d755.png)

We'll also want to include a string above the readout the specifies the ranges for the values (velocity still TBD, but mass is tentatively 0.1-10 kg), which was done in `projectile-motion`.

![image](https://user-images.githubusercontent.com/8419308/66225828-a6d57280-e696-11e9-94b6-ae9ceb5c1b39.png)

**Comment by brandonLi8** [comment]
@arouinfar `Keypad` has multiple layouts. I think the one to use for `collision-lab` looks like
![image](https://user-images.githubusercontent.com/42391580/82628391-f1661980-9ba9-11ea-8b22-f51a2197674c.png)


which has the decimal and +/-.

**Comment by brandonLi8** [comment]
The panel was finished in #58. The only thing left is to position the keypad correctly, which ill do in a separate issue. Closing.
