### ISSUE TITLE
Create a scenery node representing a X.

### ISSUE THREAD

**Issue by veillette** [phetsims/collision-lab#30]
![image](https://user-images.githubusercontent.com/7633344/66150747-d4151880-e5e3-11e9-85f3-272db160fc18.png)

The API should be such that it takes options as argument where the options is an Object with 
 fill, stroke, linewidth, size and thickness. These five variables should be enough to draw the X.

One may be able to leverage PlusNode in SceneryPhet by rotating it 45 degrees.

**Comment by alex-schor** [comment]
I created a scenery node for the X. It does not currently support having a thicker border on the ends of the X as shown in the image posted above, but I don't see that thicker border present in the mockups in the design document. As I believe the node is complete, I am assigning to @veillette for review.

**Comment by arouinfar** [comment]
> but I don't see that thicker border present in the mockups in the design document.

Correct @alex-schor. The screenshot in https://github.com/phetsims/collision-lab/issues/30#issue-502207864 is from the original Flash sim, but the stroke in the HTML5 design is uniform.

![image](https://user-images.githubusercontent.com/8419308/66261806-6c9ccb80-e791-11e9-9f40-be30b32bf8b5.png)

**Comment by brandonLi8** [comment]
I went ahead and did a review. @veillette feel free to comment or add on.

Overall, I think this Node looks **good**. Specifically:
- Good documentation of the `VerticesOffset`
- Good documentation of the drawing of the x shape
- Simple and straightforward implementation. Looks really good!

<br>

## Some possible changes to ponder:
- [ ] The options are not passed to the super class. This is what you have:
```
  class XNode extends Node {
    ...
    constructor( options ) {

      super();
      options = ...
```
This is problematic because the name (XNode) portrays itself as a Node. Yet if I did something like
```
 xNode = new XNode( {
     left: 135 // arbitrary number
 } );
```
(giving it an option that Node contains) it wouldn't position the based on the options. My recommendation would be to just pass options right into the super call.
- [ ] This one is a little more up in the air. Currently, this node extends Node.js. However, it doesn't make much use of the super class Node. Here is the scene graph:
```
      Super (Node)
         |
      XPath (Path)
```
The super class only has one child (XPath) which itself extends Node. A simpler approach could be to extend Path and just pass the xShape to the super class along with the options. @veillette what are your thoughts? I'm fine with either option.

<br> 

Otherwise, I think it looks good. Back to @alex-schor.

**Comment by alex-schor** [comment]
@brandonLi8 I changed XNode to XPath, now it extends Path instead of Node. The options are passed to the superclass. Added fill and stroke colors to CollisionLabColors.js

**Comment by alex-schor** [comment]
Assigning back to @brandonLi8 for closing
