### ISSUE TITLE
Reset button does not reset the velocity and position of the balls

### ISSUE THREAD

**Issue by veillette** [phetsims/collision-lab#45]
THe reset button reset the number of balls but not the position and velocity of the balls.

**Comment by veillette** [comment]
The prepopulated array for the initial balls needs to be emptied out.

**Comment by brandonLi8** [comment]
The prepopulated array does not need to be emptied out. When the reset method is called, the `numberOfBallsProperty` is reset and that should change its value to make the correct number of Balls in the Balls Observable Array.

However, you have 
```
        // remove ball(s) from observableArray
        this.balls.splice( oldValue -1, Math.abs( difference ) );
```

This will start removing at the oldValue index forwards, but since the oldValue is the length of the observable array before removing, index - 1 is the index of the last element. This will only remove 1 element no matter how large difference is (because it only removes **forwards**.

**Comment by brandonLi8** [comment]
In the commit above, this is fixed. It now looks like
```
        // remove ball(s) from observableArray
        this.balls.splice( oldValue + difference, Math.abs( difference ) );
```
This will correctly remove the correct number of balls from the correct index. Closing.
