### ISSUE TITLE
label values with units

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/collision-lab#96]
Something I noticed while looking at #93....

Many of the values displayed have units next to them. For example:

<img width="135" alt="screenshot_392" src="https://user-images.githubusercontent.com/3046552/84594746-9d013300-ae11-11ea-9e2b-52069b2d75a1.png">
<img width="147" alt="screenshot_393" src="https://user-images.githubusercontent.com/3046552/84594748-9e326000-ae11-11ea-8efe-281c7d4fc719.png">
<img width="256" alt="screenshot_395" src="https://user-images.githubusercontent.com/3046552/84594750-9ecaf680-ae11-11ea-8db8-88d75d568912.png">

Then there's this panel:

<img width="639" alt="screenshot_396" src="https://user-images.githubusercontent.com/3046552/84594752-a4284100-ae11-11ea-8391-f860af8474cf.png">

If it were me, I'd put the units next to the values in this panel too, instead of next to the column headings. You have the space, and I think it would make the display read easier.   It would also clean up the column headings, so that some of them wouldn't need to be 2 lines.

**Comment by brandonLi8** [comment]
@pixelzoom keep in mind that in the "Explore 2D" screen there are more fields to this panel:
![image](https://user-images.githubusercontent.com/42391580/84926854-39813a80-b089-11ea-843a-2adb0cb60f00.png)

We may not have enough room for units (especially since the units for momentum are really long) as it could extend into the Momenta Diagram.

**Comment by brandonLi8** [comment]
From design meeting 6/25/20, we decided that we didn't have enough room for units and we were fine leaving it as-is. Closing.
